# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pycloud_v1_pb2 as pycloud__v1__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pycloud_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeControlServiceStub(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCode = channel.stream_unary(
                '/pycloud.v1.NodeControlService/UploadCode',
                request_serializer=pycloud__v1__pb2.UploadCodeRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UploadCodeResponse.FromString,
                _registered_method=True)
        self.UploadObject = channel.stream_unary(
                '/pycloud.v1.NodeControlService/UploadObject',
                request_serializer=pycloud__v1__pb2.UploadObjectRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UploadObjectResponse.FromString,
                _registered_method=True)
        self.DownloadObject = channel.unary_stream(
                '/pycloud.v1.NodeControlService/DownloadObject',
                request_serializer=pycloud__v1__pb2.DownloadObjectRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.DownloadObjectChunk.FromString,
                _registered_method=True)
        self.UpdateRuntimeGlobals = channel.unary_unary(
                '/pycloud.v1.NodeControlService/UpdateRuntimeGlobals',
                request_serializer=pycloud__v1__pb2.UpdateRuntimeGlobalsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UpdateRuntimeGlobalsResponse.FromString,
                _registered_method=True)
        self.TaskStream = channel.stream_stream(
                '/pycloud.v1.NodeControlService/TaskStream',
                request_serializer=pycloud__v1__pb2.TaskStreamRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.TaskStreamResponse.FromString,
                _registered_method=True)
        self.SubmitTasks = channel.unary_unary(
                '/pycloud.v1.NodeControlService/SubmitTasks',
                request_serializer=pycloud__v1__pb2.SubmitTasksRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.SubmitTasksResponse.FromString,
                _registered_method=True)
        self.PullResults = channel.unary_unary(
                '/pycloud.v1.NodeControlService/PullResults',
                request_serializer=pycloud__v1__pb2.PullResultsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.PullResultsResponse.FromString,
                _registered_method=True)
        self.CancelTasks = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CancelTasks',
                request_serializer=pycloud__v1__pb2.CancelTasksRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CancelTasksResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CancelJob',
                request_serializer=pycloud__v1__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/pycloud.v1.NodeControlService/GetMetrics',
                request_serializer=pycloud__v1__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.CreateService = channel.stream_unary(
                '/pycloud.v1.NodeControlService/CreateService',
                request_serializer=pycloud__v1__pb2.CreateServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CreateServiceResponse.FromString,
                _registered_method=True)
        self.ListServiceMethods = channel.unary_unary(
                '/pycloud.v1.NodeControlService/ListServiceMethods',
                request_serializer=pycloud__v1__pb2.ListServiceMethodsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.ListServiceMethodsResponse.FromString,
                _registered_method=True)
        self.CallService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CallService',
                request_serializer=pycloud__v1__pb2.CallServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CallServiceResponse.FromString,
                _registered_method=True)
        self.UpdateServiceGlobals = channel.unary_unary(
                '/pycloud.v1.NodeControlService/UpdateServiceGlobals',
                request_serializer=pycloud__v1__pb2.UpdateServiceGlobalsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UpdateServiceGlobalsResponse.FromString,
                _registered_method=True)
        self.HeartbeatService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/HeartbeatService',
                request_serializer=pycloud__v1__pb2.HeartbeatServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.HeartbeatServiceResponse.FromString,
                _registered_method=True)
        self.EndService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/EndService',
                request_serializer=pycloud__v1__pb2.EndServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.EndServiceResponse.FromString,
                _registered_method=True)
        self.GetServiceStatus = channel.unary_unary(
                '/pycloud.v1.NodeControlService/GetServiceStatus',
                request_serializer=pycloud__v1__pb2.GetServiceStatusRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.GetServiceStatusResponse.FromString,
                _registered_method=True)


class NodeControlServiceServicer(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    def UploadCode(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadObject(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRuntimeGlobals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateService(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateServiceGlobals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCode': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadCode,
                    request_deserializer=pycloud__v1__pb2.UploadCodeRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UploadCodeResponse.SerializeToString,
            ),
            'UploadObject': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadObject,
                    request_deserializer=pycloud__v1__pb2.UploadObjectRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UploadObjectResponse.SerializeToString,
            ),
            'DownloadObject': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadObject,
                    request_deserializer=pycloud__v1__pb2.DownloadObjectRequest.FromString,
                    response_serializer=pycloud__v1__pb2.DownloadObjectChunk.SerializeToString,
            ),
            'UpdateRuntimeGlobals': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRuntimeGlobals,
                    request_deserializer=pycloud__v1__pb2.UpdateRuntimeGlobalsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UpdateRuntimeGlobalsResponse.SerializeToString,
            ),
            'TaskStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=pycloud__v1__pb2.TaskStreamRequest.FromString,
                    response_serializer=pycloud__v1__pb2.TaskStreamResponse.SerializeToString,
            ),
            'SubmitTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTasks,
                    request_deserializer=pycloud__v1__pb2.SubmitTasksRequest.FromString,
                    response_serializer=pycloud__v1__pb2.SubmitTasksResponse.SerializeToString,
            ),
            'PullResults': grpc.unary_unary_rpc_method_handler(
                    servicer.PullResults,
                    request_deserializer=pycloud__v1__pb2.PullResultsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.PullResultsResponse.SerializeToString,
            ),
            'CancelTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTasks,
                    request_deserializer=pycloud__v1__pb2.CancelTasksRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CancelTasksResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=pycloud__v1__pb2.CancelJobRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CancelJobResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=pycloud__v1__pb2.GetMetricsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.GetMetricsResponse.SerializeToString,
            ),
            'CreateService': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateService,
                    request_deserializer=pycloud__v1__pb2.CreateServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CreateServiceResponse.SerializeToString,
            ),
            'ListServiceMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceMethods,
                    request_deserializer=pycloud__v1__pb2.ListServiceMethodsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.ListServiceMethodsResponse.SerializeToString,
            ),
            'CallService': grpc.unary_unary_rpc_method_handler(
                    servicer.CallService,
                    request_deserializer=pycloud__v1__pb2.CallServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CallServiceResponse.SerializeToString,
            ),
            'UpdateServiceGlobals': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateServiceGlobals,
                    request_deserializer=pycloud__v1__pb2.UpdateServiceGlobalsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UpdateServiceGlobalsResponse.SerializeToString,
            ),
            'HeartbeatService': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatService,
                    request_deserializer=pycloud__v1__pb2.HeartbeatServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.HeartbeatServiceResponse.SerializeToString,
            ),
            'EndService': grpc.unary_unary_rpc_method_handler(
                    servicer.EndService,
                    request_deserializer=pycloud__v1__pb2.EndServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.EndServiceResponse.SerializeToString,
            ),
            'GetServiceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStatus,
                    request_deserializer=pycloud__v1__pb2.GetServiceStatusRequest.FromString,
                    response_serializer=pycloud__v1__pb2.GetServiceStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pycloud.v1.NodeControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pycloud.v1.NodeControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeControlService(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    @staticmethod
    def UploadCode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/UploadCode',
            pycloud__v1__pb2.UploadCodeRequest.SerializeToString,
            pycloud__v1__pb2.UploadCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadObject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/UploadObject',
            pycloud__v1__pb2.UploadObjectRequest.SerializeToString,
            pycloud__v1__pb2.UploadObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pycloud.v1.NodeControlService/DownloadObject',
            pycloud__v1__pb2.DownloadObjectRequest.SerializeToString,
            pycloud__v1__pb2.DownloadObjectChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRuntimeGlobals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/UpdateRuntimeGlobals',
            pycloud__v1__pb2.UpdateRuntimeGlobalsRequest.SerializeToString,
            pycloud__v1__pb2.UpdateRuntimeGlobalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/TaskStream',
            pycloud__v1__pb2.TaskStreamRequest.SerializeToString,
            pycloud__v1__pb2.TaskStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/SubmitTasks',
            pycloud__v1__pb2.SubmitTasksRequest.SerializeToString,
            pycloud__v1__pb2.SubmitTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/PullResults',
            pycloud__v1__pb2.PullResultsRequest.SerializeToString,
            pycloud__v1__pb2.PullResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CancelTasks',
            pycloud__v1__pb2.CancelTasksRequest.SerializeToString,
            pycloud__v1__pb2.CancelTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CancelJob',
            pycloud__v1__pb2.CancelJobRequest.SerializeToString,
            pycloud__v1__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/GetMetrics',
            pycloud__v1__pb2.GetMetricsRequest.SerializeToString,
            pycloud__v1__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/CreateService',
            pycloud__v1__pb2.CreateServiceRequest.SerializeToString,
            pycloud__v1__pb2.CreateServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/ListServiceMethods',
            pycloud__v1__pb2.ListServiceMethodsRequest.SerializeToString,
            pycloud__v1__pb2.ListServiceMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CallService',
            pycloud__v1__pb2.CallServiceRequest.SerializeToString,
            pycloud__v1__pb2.CallServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateServiceGlobals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/UpdateServiceGlobals',
            pycloud__v1__pb2.UpdateServiceGlobalsRequest.SerializeToString,
            pycloud__v1__pb2.UpdateServiceGlobalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/HeartbeatService',
            pycloud__v1__pb2.HeartbeatServiceRequest.SerializeToString,
            pycloud__v1__pb2.HeartbeatServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/EndService',
            pycloud__v1__pb2.EndServiceRequest.SerializeToString,
            pycloud__v1__pb2.EndServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/GetServiceStatus',
            pycloud__v1__pb2.GetServiceStatusRequest.SerializeToString,
            pycloud__v1__pb2.GetServiceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
