# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pycloud_v1_pb2 as pycloud__v1__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pycloud_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InfoCenterServiceStub(object):
    """-------------------------
    InfoCenter service
    -------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/pycloud.v1.InfoCenterService/RegisterNode',
                request_serializer=pycloud__v1__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.HeartbeatNode = channel.unary_unary(
                '/pycloud.v1.InfoCenterService/HeartbeatNode',
                request_serializer=pycloud__v1__pb2.HeartbeatNodeRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.HeartbeatNodeResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/pycloud.v1.InfoCenterService/ListNodes',
                request_serializer=pycloud__v1__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.ListServiceRoutes = channel.unary_unary(
                '/pycloud.v1.InfoCenterService/ListServiceRoutes',
                request_serializer=pycloud__v1__pb2.ListServiceRoutesRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.ListServiceRoutesResponse.FromString,
                _registered_method=True)


class InfoCenterServiceServicer(object):
    """-------------------------
    InfoCenter service
    -------------------------

    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InfoCenterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=pycloud__v1__pb2.RegisterNodeRequest.FromString,
                    response_serializer=pycloud__v1__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'HeartbeatNode': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatNode,
                    request_deserializer=pycloud__v1__pb2.HeartbeatNodeRequest.FromString,
                    response_serializer=pycloud__v1__pb2.HeartbeatNodeResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=pycloud__v1__pb2.ListNodesRequest.FromString,
                    response_serializer=pycloud__v1__pb2.ListNodesResponse.SerializeToString,
            ),
            'ListServiceRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceRoutes,
                    request_deserializer=pycloud__v1__pb2.ListServiceRoutesRequest.FromString,
                    response_serializer=pycloud__v1__pb2.ListServiceRoutesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pycloud.v1.InfoCenterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pycloud.v1.InfoCenterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InfoCenterService(object):
    """-------------------------
    InfoCenter service
    -------------------------

    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.InfoCenterService/RegisterNode',
            pycloud__v1__pb2.RegisterNodeRequest.SerializeToString,
            pycloud__v1__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.InfoCenterService/HeartbeatNode',
            pycloud__v1__pb2.HeartbeatNodeRequest.SerializeToString,
            pycloud__v1__pb2.HeartbeatNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.InfoCenterService/ListNodes',
            pycloud__v1__pb2.ListNodesRequest.SerializeToString,
            pycloud__v1__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.InfoCenterService/ListServiceRoutes',
            pycloud__v1__pb2.ListServiceRoutesRequest.SerializeToString,
            pycloud__v1__pb2.ListServiceRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeControlServiceStub(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCode = channel.stream_unary(
                '/pycloud.v1.NodeControlService/UploadCode',
                request_serializer=pycloud__v1__pb2.UploadCodeRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UploadCodeResponse.FromString,
                _registered_method=True)
        self.SubmitTasks = channel.unary_unary(
                '/pycloud.v1.NodeControlService/SubmitTasks',
                request_serializer=pycloud__v1__pb2.SubmitTasksRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.SubmitTasksResponse.FromString,
                _registered_method=True)
        self.PullResults = channel.unary_unary(
                '/pycloud.v1.NodeControlService/PullResults',
                request_serializer=pycloud__v1__pb2.PullResultsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.PullResultsResponse.FromString,
                _registered_method=True)
        self.CancelTasks = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CancelTasks',
                request_serializer=pycloud__v1__pb2.CancelTasksRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CancelTasksResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/pycloud.v1.NodeControlService/GetMetrics',
                request_serializer=pycloud__v1__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.CreateService = channel.stream_unary(
                '/pycloud.v1.NodeControlService/CreateService',
                request_serializer=pycloud__v1__pb2.CreateServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CreateServiceResponse.FromString,
                _registered_method=True)
        self.ListServiceMethods = channel.unary_unary(
                '/pycloud.v1.NodeControlService/ListServiceMethods',
                request_serializer=pycloud__v1__pb2.ListServiceMethodsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.ListServiceMethodsResponse.FromString,
                _registered_method=True)
        self.CallService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CallService',
                request_serializer=pycloud__v1__pb2.CallServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CallServiceResponse.FromString,
                _registered_method=True)
        self.HeartbeatService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/HeartbeatService',
                request_serializer=pycloud__v1__pb2.HeartbeatServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.HeartbeatServiceResponse.FromString,
                _registered_method=True)
        self.EndService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/EndService',
                request_serializer=pycloud__v1__pb2.EndServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.EndServiceResponse.FromString,
                _registered_method=True)
        self.GetServiceStatus = channel.unary_unary(
                '/pycloud.v1.NodeControlService/GetServiceStatus',
                request_serializer=pycloud__v1__pb2.GetServiceStatusRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.GetServiceStatusResponse.FromString,
                _registered_method=True)


class NodeControlServiceServicer(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    def UploadCode(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateService(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCode': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadCode,
                    request_deserializer=pycloud__v1__pb2.UploadCodeRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UploadCodeResponse.SerializeToString,
            ),
            'SubmitTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTasks,
                    request_deserializer=pycloud__v1__pb2.SubmitTasksRequest.FromString,
                    response_serializer=pycloud__v1__pb2.SubmitTasksResponse.SerializeToString,
            ),
            'PullResults': grpc.unary_unary_rpc_method_handler(
                    servicer.PullResults,
                    request_deserializer=pycloud__v1__pb2.PullResultsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.PullResultsResponse.SerializeToString,
            ),
            'CancelTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTasks,
                    request_deserializer=pycloud__v1__pb2.CancelTasksRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CancelTasksResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=pycloud__v1__pb2.GetMetricsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.GetMetricsResponse.SerializeToString,
            ),
            'CreateService': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateService,
                    request_deserializer=pycloud__v1__pb2.CreateServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CreateServiceResponse.SerializeToString,
            ),
            'ListServiceMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceMethods,
                    request_deserializer=pycloud__v1__pb2.ListServiceMethodsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.ListServiceMethodsResponse.SerializeToString,
            ),
            'CallService': grpc.unary_unary_rpc_method_handler(
                    servicer.CallService,
                    request_deserializer=pycloud__v1__pb2.CallServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CallServiceResponse.SerializeToString,
            ),
            'HeartbeatService': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatService,
                    request_deserializer=pycloud__v1__pb2.HeartbeatServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.HeartbeatServiceResponse.SerializeToString,
            ),
            'EndService': grpc.unary_unary_rpc_method_handler(
                    servicer.EndService,
                    request_deserializer=pycloud__v1__pb2.EndServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.EndServiceResponse.SerializeToString,
            ),
            'GetServiceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStatus,
                    request_deserializer=pycloud__v1__pb2.GetServiceStatusRequest.FromString,
                    response_serializer=pycloud__v1__pb2.GetServiceStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pycloud.v1.NodeControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pycloud.v1.NodeControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeControlService(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    @staticmethod
    def UploadCode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/UploadCode',
            pycloud__v1__pb2.UploadCodeRequest.SerializeToString,
            pycloud__v1__pb2.UploadCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/SubmitTasks',
            pycloud__v1__pb2.SubmitTasksRequest.SerializeToString,
            pycloud__v1__pb2.SubmitTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/PullResults',
            pycloud__v1__pb2.PullResultsRequest.SerializeToString,
            pycloud__v1__pb2.PullResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CancelTasks',
            pycloud__v1__pb2.CancelTasksRequest.SerializeToString,
            pycloud__v1__pb2.CancelTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/GetMetrics',
            pycloud__v1__pb2.GetMetricsRequest.SerializeToString,
            pycloud__v1__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/CreateService',
            pycloud__v1__pb2.CreateServiceRequest.SerializeToString,
            pycloud__v1__pb2.CreateServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/ListServiceMethods',
            pycloud__v1__pb2.ListServiceMethodsRequest.SerializeToString,
            pycloud__v1__pb2.ListServiceMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CallService',
            pycloud__v1__pb2.CallServiceRequest.SerializeToString,
            pycloud__v1__pb2.CallServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/HeartbeatService',
            pycloud__v1__pb2.HeartbeatServiceRequest.SerializeToString,
            pycloud__v1__pb2.HeartbeatServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/EndService',
            pycloud__v1__pb2.EndServiceRequest.SerializeToString,
            pycloud__v1__pb2.EndServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/GetServiceStatus',
            pycloud__v1__pb2.GetServiceStatusRequest.SerializeToString,
            pycloud__v1__pb2.GetServiceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerInternalServiceStub(object):
    """-------------------------
    Worker internal service (local)
    -------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PollTask = channel.unary_unary(
                '/pycloud.v1.WorkerInternalService/PollTask',
                request_serializer=pycloud__v1__pb2.PollTaskRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.PollTaskResponse.FromString,
                _registered_method=True)
        self.HeartbeatTask = channel.unary_unary(
                '/pycloud.v1.WorkerInternalService/HeartbeatTask',
                request_serializer=pycloud__v1__pb2.HeartbeatTaskRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.HeartbeatTaskResponse.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/pycloud.v1.WorkerInternalService/ReportResult',
                request_serializer=pycloud__v1__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.ReportResultResponse.FromString,
                _registered_method=True)


class WorkerInternalServiceServicer(object):
    """-------------------------
    Worker internal service (local)
    -------------------------

    """

    def PollTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerInternalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PollTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollTask,
                    request_deserializer=pycloud__v1__pb2.PollTaskRequest.FromString,
                    response_serializer=pycloud__v1__pb2.PollTaskResponse.SerializeToString,
            ),
            'HeartbeatTask': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatTask,
                    request_deserializer=pycloud__v1__pb2.HeartbeatTaskRequest.FromString,
                    response_serializer=pycloud__v1__pb2.HeartbeatTaskResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=pycloud__v1__pb2.ReportResultRequest.FromString,
                    response_serializer=pycloud__v1__pb2.ReportResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pycloud.v1.WorkerInternalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pycloud.v1.WorkerInternalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerInternalService(object):
    """-------------------------
    Worker internal service (local)
    -------------------------

    """

    @staticmethod
    def PollTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.WorkerInternalService/PollTask',
            pycloud__v1__pb2.PollTaskRequest.SerializeToString,
            pycloud__v1__pb2.PollTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.WorkerInternalService/HeartbeatTask',
            pycloud__v1__pb2.HeartbeatTaskRequest.SerializeToString,
            pycloud__v1__pb2.HeartbeatTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.WorkerInternalService/ReportResult',
            pycloud__v1__pb2.ReportResultRequest.SerializeToString,
            pycloud__v1__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
