# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pycloud_v1_pb2 as pycloud__v1__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pycloud_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeControlServiceStub(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCode = channel.stream_unary(
                '/pycloud.v1.NodeControlService/UploadCode',
                request_serializer=pycloud__v1__pb2.UploadCodeRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UploadCodeResponse.FromString,
                _registered_method=True)
        self.UploadObject = channel.stream_unary(
                '/pycloud.v1.NodeControlService/UploadObject',
                request_serializer=pycloud__v1__pb2.UploadObjectRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UploadObjectResponse.FromString,
                _registered_method=True)
        self.DownloadObject = channel.unary_stream(
                '/pycloud.v1.NodeControlService/DownloadObject',
                request_serializer=pycloud__v1__pb2.DownloadObjectRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.DownloadObjectChunk.FromString,
                _registered_method=True)
        self.PinObject = channel.unary_unary(
                '/pycloud.v1.NodeControlService/PinObject',
                request_serializer=pycloud__v1__pb2.PinObjectRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.PinObjectResponse.FromString,
                _registered_method=True)
        self.ReleaseObject = channel.unary_unary(
                '/pycloud.v1.NodeControlService/ReleaseObject',
                request_serializer=pycloud__v1__pb2.ReleaseObjectRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.ReleaseObjectResponse.FromString,
                _registered_method=True)
        self.UpdateRuntimeGlobals = channel.unary_unary(
                '/pycloud.v1.NodeControlService/UpdateRuntimeGlobals',
                request_serializer=pycloud__v1__pb2.UpdateRuntimeGlobalsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UpdateRuntimeGlobalsResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/pycloud.v1.NodeControlService/GetMetrics',
                request_serializer=pycloud__v1__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.CreateTaskPool = channel.stream_unary(
                '/pycloud.v1.NodeControlService/CreateTaskPool',
                request_serializer=pycloud__v1__pb2.CreateTaskPoolRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CreateTaskPoolResponse.FromString,
                _registered_method=True)
        self.HeartbeatTaskPool = channel.unary_unary(
                '/pycloud.v1.NodeControlService/HeartbeatTaskPool',
                request_serializer=pycloud__v1__pb2.HeartbeatTaskPoolRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.HeartbeatTaskPoolResponse.FromString,
                _registered_method=True)
        self.SubmitPoolTasks = channel.unary_unary(
                '/pycloud.v1.NodeControlService/SubmitPoolTasks',
                request_serializer=pycloud__v1__pb2.SubmitPoolTasksRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.SubmitTasksResponse.FromString,
                _registered_method=True)
        self.PullPoolResults = channel.unary_unary(
                '/pycloud.v1.NodeControlService/PullPoolResults',
                request_serializer=pycloud__v1__pb2.PullPoolResultsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.PullResultsResponse.FromString,
                _registered_method=True)
        self.CancelPoolJob = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CancelPoolJob',
                request_serializer=pycloud__v1__pb2.CancelPoolJobRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.GetTaskPoolStatus = channel.unary_unary(
                '/pycloud.v1.NodeControlService/GetTaskPoolStatus',
                request_serializer=pycloud__v1__pb2.GetTaskPoolStatusRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.GetTaskPoolStatusResponse.FromString,
                _registered_method=True)
        self.CloseTaskPool = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CloseTaskPool',
                request_serializer=pycloud__v1__pb2.CloseTaskPoolRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CloseTaskPoolResponse.FromString,
                _registered_method=True)
        self.CreateService = channel.stream_unary(
                '/pycloud.v1.NodeControlService/CreateService',
                request_serializer=pycloud__v1__pb2.CreateServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CreateServiceResponse.FromString,
                _registered_method=True)
        self.ListServiceMethods = channel.unary_unary(
                '/pycloud.v1.NodeControlService/ListServiceMethods',
                request_serializer=pycloud__v1__pb2.ListServiceMethodsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.ListServiceMethodsResponse.FromString,
                _registered_method=True)
        self.CallService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/CallService',
                request_serializer=pycloud__v1__pb2.CallServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.CallServiceResponse.FromString,
                _registered_method=True)
        self.UpdateServiceGlobals = channel.unary_unary(
                '/pycloud.v1.NodeControlService/UpdateServiceGlobals',
                request_serializer=pycloud__v1__pb2.UpdateServiceGlobalsRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.UpdateServiceGlobalsResponse.FromString,
                _registered_method=True)
        self.HeartbeatService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/HeartbeatService',
                request_serializer=pycloud__v1__pb2.HeartbeatServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.HeartbeatServiceResponse.FromString,
                _registered_method=True)
        self.EndService = channel.unary_unary(
                '/pycloud.v1.NodeControlService/EndService',
                request_serializer=pycloud__v1__pb2.EndServiceRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.EndServiceResponse.FromString,
                _registered_method=True)
        self.GetServiceStatus = channel.unary_unary(
                '/pycloud.v1.NodeControlService/GetServiceStatus',
                request_serializer=pycloud__v1__pb2.GetServiceStatusRequest.SerializeToString,
                response_deserializer=pycloud__v1__pb2.GetServiceStatusResponse.FromString,
                _registered_method=True)


class NodeControlServiceServicer(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    def UploadCode(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadObject(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PinObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRuntimeGlobals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTaskPool(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatTaskPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPoolTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullPoolResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPoolJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskPoolStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseTaskPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateService(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateServiceGlobals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCode': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadCode,
                    request_deserializer=pycloud__v1__pb2.UploadCodeRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UploadCodeResponse.SerializeToString,
            ),
            'UploadObject': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadObject,
                    request_deserializer=pycloud__v1__pb2.UploadObjectRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UploadObjectResponse.SerializeToString,
            ),
            'DownloadObject': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadObject,
                    request_deserializer=pycloud__v1__pb2.DownloadObjectRequest.FromString,
                    response_serializer=pycloud__v1__pb2.DownloadObjectChunk.SerializeToString,
            ),
            'PinObject': grpc.unary_unary_rpc_method_handler(
                    servicer.PinObject,
                    request_deserializer=pycloud__v1__pb2.PinObjectRequest.FromString,
                    response_serializer=pycloud__v1__pb2.PinObjectResponse.SerializeToString,
            ),
            'ReleaseObject': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseObject,
                    request_deserializer=pycloud__v1__pb2.ReleaseObjectRequest.FromString,
                    response_serializer=pycloud__v1__pb2.ReleaseObjectResponse.SerializeToString,
            ),
            'UpdateRuntimeGlobals': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRuntimeGlobals,
                    request_deserializer=pycloud__v1__pb2.UpdateRuntimeGlobalsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UpdateRuntimeGlobalsResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=pycloud__v1__pb2.GetMetricsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.GetMetricsResponse.SerializeToString,
            ),
            'CreateTaskPool': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateTaskPool,
                    request_deserializer=pycloud__v1__pb2.CreateTaskPoolRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CreateTaskPoolResponse.SerializeToString,
            ),
            'HeartbeatTaskPool': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatTaskPool,
                    request_deserializer=pycloud__v1__pb2.HeartbeatTaskPoolRequest.FromString,
                    response_serializer=pycloud__v1__pb2.HeartbeatTaskPoolResponse.SerializeToString,
            ),
            'SubmitPoolTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPoolTasks,
                    request_deserializer=pycloud__v1__pb2.SubmitPoolTasksRequest.FromString,
                    response_serializer=pycloud__v1__pb2.SubmitTasksResponse.SerializeToString,
            ),
            'PullPoolResults': grpc.unary_unary_rpc_method_handler(
                    servicer.PullPoolResults,
                    request_deserializer=pycloud__v1__pb2.PullPoolResultsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.PullResultsResponse.SerializeToString,
            ),
            'CancelPoolJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPoolJob,
                    request_deserializer=pycloud__v1__pb2.CancelPoolJobRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CancelJobResponse.SerializeToString,
            ),
            'GetTaskPoolStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskPoolStatus,
                    request_deserializer=pycloud__v1__pb2.GetTaskPoolStatusRequest.FromString,
                    response_serializer=pycloud__v1__pb2.GetTaskPoolStatusResponse.SerializeToString,
            ),
            'CloseTaskPool': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseTaskPool,
                    request_deserializer=pycloud__v1__pb2.CloseTaskPoolRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CloseTaskPoolResponse.SerializeToString,
            ),
            'CreateService': grpc.stream_unary_rpc_method_handler(
                    servicer.CreateService,
                    request_deserializer=pycloud__v1__pb2.CreateServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CreateServiceResponse.SerializeToString,
            ),
            'ListServiceMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceMethods,
                    request_deserializer=pycloud__v1__pb2.ListServiceMethodsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.ListServiceMethodsResponse.SerializeToString,
            ),
            'CallService': grpc.unary_unary_rpc_method_handler(
                    servicer.CallService,
                    request_deserializer=pycloud__v1__pb2.CallServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.CallServiceResponse.SerializeToString,
            ),
            'UpdateServiceGlobals': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateServiceGlobals,
                    request_deserializer=pycloud__v1__pb2.UpdateServiceGlobalsRequest.FromString,
                    response_serializer=pycloud__v1__pb2.UpdateServiceGlobalsResponse.SerializeToString,
            ),
            'HeartbeatService': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatService,
                    request_deserializer=pycloud__v1__pb2.HeartbeatServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.HeartbeatServiceResponse.SerializeToString,
            ),
            'EndService': grpc.unary_unary_rpc_method_handler(
                    servicer.EndService,
                    request_deserializer=pycloud__v1__pb2.EndServiceRequest.FromString,
                    response_serializer=pycloud__v1__pb2.EndServiceResponse.SerializeToString,
            ),
            'GetServiceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStatus,
                    request_deserializer=pycloud__v1__pb2.GetServiceStatusRequest.FromString,
                    response_serializer=pycloud__v1__pb2.GetServiceStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pycloud.v1.NodeControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pycloud.v1.NodeControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeControlService(object):
    """-------------------------
    NodeControl service (client facing)
    -------------------------

    """

    @staticmethod
    def UploadCode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/UploadCode',
            pycloud__v1__pb2.UploadCodeRequest.SerializeToString,
            pycloud__v1__pb2.UploadCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadObject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/UploadObject',
            pycloud__v1__pb2.UploadObjectRequest.SerializeToString,
            pycloud__v1__pb2.UploadObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pycloud.v1.NodeControlService/DownloadObject',
            pycloud__v1__pb2.DownloadObjectRequest.SerializeToString,
            pycloud__v1__pb2.DownloadObjectChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PinObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/PinObject',
            pycloud__v1__pb2.PinObjectRequest.SerializeToString,
            pycloud__v1__pb2.PinObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/ReleaseObject',
            pycloud__v1__pb2.ReleaseObjectRequest.SerializeToString,
            pycloud__v1__pb2.ReleaseObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRuntimeGlobals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/UpdateRuntimeGlobals',
            pycloud__v1__pb2.UpdateRuntimeGlobalsRequest.SerializeToString,
            pycloud__v1__pb2.UpdateRuntimeGlobalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/GetMetrics',
            pycloud__v1__pb2.GetMetricsRequest.SerializeToString,
            pycloud__v1__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTaskPool(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/CreateTaskPool',
            pycloud__v1__pb2.CreateTaskPoolRequest.SerializeToString,
            pycloud__v1__pb2.CreateTaskPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatTaskPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/HeartbeatTaskPool',
            pycloud__v1__pb2.HeartbeatTaskPoolRequest.SerializeToString,
            pycloud__v1__pb2.HeartbeatTaskPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPoolTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/SubmitPoolTasks',
            pycloud__v1__pb2.SubmitPoolTasksRequest.SerializeToString,
            pycloud__v1__pb2.SubmitTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullPoolResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/PullPoolResults',
            pycloud__v1__pb2.PullPoolResultsRequest.SerializeToString,
            pycloud__v1__pb2.PullResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPoolJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CancelPoolJob',
            pycloud__v1__pb2.CancelPoolJobRequest.SerializeToString,
            pycloud__v1__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskPoolStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/GetTaskPoolStatus',
            pycloud__v1__pb2.GetTaskPoolStatusRequest.SerializeToString,
            pycloud__v1__pb2.GetTaskPoolStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseTaskPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CloseTaskPool',
            pycloud__v1__pb2.CloseTaskPoolRequest.SerializeToString,
            pycloud__v1__pb2.CloseTaskPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pycloud.v1.NodeControlService/CreateService',
            pycloud__v1__pb2.CreateServiceRequest.SerializeToString,
            pycloud__v1__pb2.CreateServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/ListServiceMethods',
            pycloud__v1__pb2.ListServiceMethodsRequest.SerializeToString,
            pycloud__v1__pb2.ListServiceMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/CallService',
            pycloud__v1__pb2.CallServiceRequest.SerializeToString,
            pycloud__v1__pb2.CallServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateServiceGlobals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/UpdateServiceGlobals',
            pycloud__v1__pb2.UpdateServiceGlobalsRequest.SerializeToString,
            pycloud__v1__pb2.UpdateServiceGlobalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/HeartbeatService',
            pycloud__v1__pb2.HeartbeatServiceRequest.SerializeToString,
            pycloud__v1__pb2.HeartbeatServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/EndService',
            pycloud__v1__pb2.EndServiceRequest.SerializeToString,
            pycloud__v1__pb2.EndServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pycloud.v1.NodeControlService/GetServiceStatus',
            pycloud__v1__pb2.GetServiceStatusRequest.SerializeToString,
            pycloud__v1__pb2.GetServiceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
